# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTTPD-Log-Filter
version:      1.08
version_from: lib/HTTPD/Log/Filter.pm
installdirs:  site
requires:
    IO::File:                      0
    IO::Zlib:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
